services:
  # ==========================================================================================================
  # ================================================ Traefik =================================================
  # ==========================================================================================================

  traefik:
    image: traefik:v2.9
    container_name: traefik
    restart: unless-stopped
    command:
      - "--api.dashboard=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=contact@enzo-palermo.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"


  # # ==========================================================================================================
  # # =============================================== phpmyadmin ===============================================
  # # ==========================================================================================================

  # phpmyadmin.enzo-palermo.com
  phpmyadmin:
    # image: phpmyadmin:5.2.2-apache
    build:
      context: ./phpmyadmin
      dockerfile: Dockerfile
    container_name: vps_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - db_lab
      - db_gmao
      - db_neptune
    environment:
      PMA_ARBITRARY: 0
      PMA_HOSTS: db_lab, db_gmao, db_neptune
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.enzo-palermo.com`)"
      - "traefik.http.routers.phpmyadmin.entrypoints=websecure"
      - "traefik.http.routers.phpmyadmin.tls=true"
      - "traefik.http.routers.phpmyadmin.tls.certresolver=myresolver"


  # ==========================================================================================================
  # ================================================ api_gmao ================================================
  # ==========================================================================================================

  # api.gmao.enzo-palermo.com
  api_gmao:
    build:
      context: ./web/api_gmao
      dockerfile: Dockerfile
    container_name: vps_web_api_gmao
    restart: unless-stopped
    ports:
      - "8081:80"
    depends_on:
      - db_gmao
    environment:
      - DATABASE_HOST=db_gmao
      - DATABASE_PORT=3306
      - DATABASE_NAME=${DB_GMAO_NAME}
      - DATABASE_USER=${DB_GMAO_USER}
      - DATABASE_PASSWORD=${DB_GMAO_PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api_gmao.rule=Host(`api.gmao.enzo-palermo.com`)"
      - "traefik.http.routers.api_gmao.entrypoints=websecure"
      - "traefik.http.routers.api_gmao.tls=true"
      - "traefik.http.routers.api_gmao.tls.certresolver=myresolver"


  # ================================================ db_gmao =================================================

  db_gmao:
    build:
      context: ./db/mysql_gmao
      dockerfile: Dockerfile
    container_name: vps_db_mysql_gmao
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_GMAO_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_GMAO_NAME}
      MYSQL_USER: ${DB_GMAO_USER}
      MYSQL_PASSWORD: ${DB_GMAO_PASSWORD}
      PMA_HOST: db_gmao
    volumes:
      - db_gmao-data:/var/lib/mysql


  # ==========================================================================================================
  # ============================================ enzo_palermo_v1 =============================================
  # ==========================================================================================================

  # enzo-palermo-v1.enzo-palermo.com
  enzo_palermo_v1:
    build:
      context: ./web/enzo_palermo_v1
      dockerfile: Dockerfile
    container_name: vps_web_enzo_palermo_v1
    restart: unless-stopped
    ports:
      - "8082:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.enzo-palermo-v1.rule=Host(`enzo-palermo-v1.enzo-palermo.com`)"
      - "traefik.http.routers.enzo-palermo-v1.entrypoints=websecure"
      - "traefik.http.routers.enzo-palermo-v1.tls=true"
      - "traefik.http.routers.enzo-palermo-v1.tls.certresolver=myresolver"


  # ==========================================================================================================
  # ================================================== gamo ==================================================
  # ==========================================================================================================

  # gmao.enzo-palermo.com
  gmao:
    build:
      context: ./web/gmao
      dockerfile: Dockerfile
    container_name: vps_web_gmao
    restart: unless-stopped
    ports:
      - "8083:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gamo.rule=Host(`gmao.enzo-palermo.com`)"
      - "traefik.http.routers.gamo.entrypoints=websecure"
      - "traefik.http.routers.gamo.tls=true"
      - "traefik.http.routers.gamo.tls.certresolver=myresolver"


  # ==========================================================================================================
  # ================================================= hi_mix =================================================
  # ==========================================================================================================

  # hi-mix.enzo-palermo.com
  hi_mix:
    build:
      context: ./web/hi-mix
      dockerfile: Dockerfile
    container_name: vps_web_hi_mix
    restart: unless-stopped
    ports:
      - "8084:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hi-mix.rule=Host(`hi-mix.enzo-palermo.com`)"
      - "traefik.http.routers.hi-mix.entrypoints=websecure"
      - "traefik.http.routers.hi-mix.tls=true"
      - "traefik.http.routers.hi-mix.tls.certresolver=myresolver"


  # ==========================================================================================================
  # ================================================== html ==================================================
  # ==========================================================================================================

  # enzo-palermo.com
  html:
    build:
      context: ./web/html
      dockerfile: Dockerfile
    container_name: vps_web_html
    restart: unless-stopped
    ports:
      - "8085:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rule=Host(`enzo-palermo.com`)"
      - "traefik.http.routers.entrypoints=websecure"
      - "traefik.http.routers.tls=true"
      - "traefik.http.routers.tls.certresolver=myresolver"


  # ==========================================================================================================
  # ================================================== lab ===================================================
  # ==========================================================================================================

  # lab.enzo-palermo.com
  lab:
    build:
      context: ./web/lab
      dockerfile: Dockerfile
    container_name: vps_web_lab
    restart: unless-stopped
    ports:
      - "8086:80"
    depends_on:
      - db_lab
    environment:
      - DATABASE_HOST=db_lab
      - DATABASE_PORT=3306
      - DATABASE_NAME=${DB_LAB_NAME}
      - DATABASE_USER=${DB_LAB_USER}
      - DATABASE_PASSWORD=${DB_LAB_PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lab.rule=Host(`lab.enzo-palermo.com`)"
      - "traefik.http.routers.lab.entrypoints=websecure"
      - "traefik.http.routers.lab.tls=true"
      - "traefik.http.routers.lab.tls.certresolver=myresolver"


  # ================================================= db_lab =================================================

  db_lab:
    build:
      context: ./db/mysql_lab
      dockerfile: Dockerfile
    container_name: vps_db_mysql_lab
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_LAB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_LAB_NAME}
      MYSQL_USER: ${DB_LAB_USER}
      MYSQL_PASSWORD: ${DB_LAB_PASSWORD}
      PMA_HOST: db_lab
    volumes:
      - db_lab-data:/var/lib/mysql


  # ==========================================================================================================
  # ============================================= projet_neptune =============================================
  # ==========================================================================================================

  # neptune.enzo-palermo.com
  projet_neptune:
    build:
      context: ./web/projet_neptune
      dockerfile: Dockerfile
    container_name: vps_web_projet_neptune
    restart: unless-stopped
    ports:
      - "8087:80"
    depends_on:
      - db_neptune
    environment:
      - DATABASE_HOST=db_neptune
      - DATABASE_PORT=3306
      - DATABASE_NAME=${DB_NEPTUNE_NAME}
      - DATABASE_USER=${DB_NEPTUNE_USER}
      - DATABASE_PASSWORD=${DB_NEPTUNE_PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.neptune.rule=Host(`neptune.enzo-palermo.com`)"
      - "traefik.http.routers.neptune.entrypoints=websecure"
      - "traefik.http.routers.neptune.tls=true"
      - "traefik.http.routers.neptune.tls.certresolver=myresolver"


  # =============================================== db_neptune ===============================================

  db_neptune:
    build:
      context: ./db/mysql_neptune
      dockerfile: Dockerfile
    container_name: vps_db_mysql_neptune
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_NEPTUNE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NEPTUNE_NAME}
      MYSQL_USER: ${DB_NEPTUNE_USER}
      MYSQL_PASSWORD: ${DB_NEPTUNE_PASSWORD}
      PMA_HOST: db_neptune
    volumes:
      - db_neptune-data:/var/lib/mysql


  # ==========================================================================================================
  # =============================================== stage_sn2 ================================================
  # ==========================================================================================================

  # stage-sn2.enzo-palermo.com
  stage_sn2:
    build:
      context: ./web/stage_sn2
      dockerfile: Dockerfile
    container_name: vps_web_stage_sn2
    restart: unless-stopped
    ports:
      - "8088:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stage-sn2.rule=Host(`stage-sn2.enzo-palermo.com`)"
      - "traefik.http.routers.stage-sn2.entrypoints=websecure"
      - "traefik.http.routers.stage-sn2.tls=true"
      - "traefik.http.routers.stage-sn2.tls.certresolver=myresolver"


  # ==========================================================================================================
  # ============================================== workshop_b3 ===============================================
  # ==========================================================================================================

  # workshop-b3.enzo-palermo.com
  workshop_b3:
    build:
      context: ./web/workshop_b3
      dockerfile: Dockerfile
    container_name: vps_web_workshop_b3
    restart: unless-stopped
    ports:
      - "8089:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.workshop-b3.rule=Host(`workshop-b3.enzo-palermo.com`)"
      - "traefik.http.routers.workshop-b3.entrypoints=websecure"
      - "traefik.http.routers.workshop-b3.tls=true"
      - "traefik.http.routers.workshop-b3.tls.certresolver=myresolver"


  # ==========================================================================================================
  # ============================================== workshop_sn1 ==============================================
  # ==========================================================================================================

  # workshop-sn1.enzo-palermo.com
  workshop_sn1:
    build:
      context: ./web/workshop_sn1
      dockerfile: Dockerfile
    container_name: vps_web_workshop_sn1
    restart: unless-stopped
    ports:
      - "8090:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.workshop_sn1.rule=Host(`workshop_sn1.enzo-palermo.com`)"
      - "traefik.http.routers.workshop_sn1.entrypoints=websecure"
      - "traefik.http.routers.workshop_sn1.tls=true"
      - "traefik.http.routers.workshop_sn1.tls.certresolver=myresolver"


  # ==========================================================================================================
  # ============================================== workshop_sn2 ==============================================
  # ==========================================================================================================

  # workshop-sn2.enzo-palermo.com
  workshop_sn2:
    build:
      context: ./web/workshop_sn2
      dockerfile: Dockerfile
    container_name: vps_web_workshop_sn2
    restart: unless-stopped
    ports:
      - "8091:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.workshop-sn2.rule=Host(`workshop-sn2.enzo-palermo.com`)"
      - "traefik.http.routers.workshop-sn2.entrypoints=websecure"
      - "traefik.http.routers.workshop-sn2.tls=true"
      - "traefik.http.routers.workshop-sn2.tls.certresolver=myresolver"


# ==========================================================================================================
# ================================================ volumes =================================================
# ==========================================================================================================

volumes:
  db_gmao-data:
  db_lab-data:
  db_neptune-data: